@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

### A simple GET request

GET http://{{host}}

### Read list of books

@route = books

GET http://{{host}}/{{route}}

### Read a single book

@route = books
@id = 1

GET http://{{host}}/{{route}}/{{id}}

### OpenAPI documentation

@api = api

GET http://{{host}}/{{api}}